/**
 * RevenueRecover AI — Global Source Registry
 * Master catalog of evaluated business and lead sources with authentication, terms, and rate limits.
 */

import { SourceRegistryEntry } from './types';

export const GLOBAL_SOURCE_REGISTRY: SourceRegistryEntry[] = [
  {
    id: 'src_google_places',
    sourceName: 'Google Places & Maps API',
    sourceType: 'SEARCH_MAPS',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'PEST_CONTROL', 'CLEANING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://developers.google.com/maps/documentation/places/web-service',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 600,
    termsUrl: 'https://cloud.google.com/maps-platform/terms',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['name', 'formatted_phone_number', 'website', 'formatted_address', 'geometry', 'rating', 'user_ratings_total', 'opening_hours', 'types'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Official Google Maps Platform API. Terms prohibit permanent caching of Place details beyond 30 days without refresh. Compliant usage for business identification.',
    estimatedCostPerCallUSD: 0.017,
  },
  {
    id: 'src_yelp_fusion',
    sourceName: 'Yelp Fusion API',
    sourceType: 'LOCAL_DIRECTORY',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'PEST_CONTROL', 'CLEANING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://docs.developer.yelp.com/docs/fusion-intro',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 300,
    termsUrl: 'https://terms.yelp.com/developer',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['name', 'phone', 'url', 'location', 'coordinates', 'rating', 'review_count', 'categories', 'is_closed'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Official Yelp Fusion API. High-accuracy ratings, verified category tags, and direct business website linking.',
    estimatedCostPerCallUSD: 0.005,
  },
  {
    id: 'src_foursquare_places',
    sourceName: 'Foursquare Places API',
    sourceType: 'SEARCH_MAPS',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'PEST_CONTROL'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://location.foursquare.com/developer/reference/places-api-overview',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 500,
    termsUrl: 'https://foursquare.com/legal/terms/api-developer',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['name', 'tel', 'website', 'location', 'geocodes', 'categories', 'verified'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Worldwide geographic business database with strong North American and European trade contractor density.',
    estimatedCostPerCallUSD: 0.003,
  },
  {
    id: 'src_bing_local',
    sourceName: 'Bing Maps & Local Search API',
    sourceType: 'SEARCH_MAPS',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'CLEANING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://learn.microsoft.com/en-us/bingmaps/rest-services/locations/',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 300,
    termsUrl: 'https://www.microsoft.com/en-us/maps/product/terms',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['name', 'phone', 'address', 'coordinates', 'business_type'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Microsoft Bing Maps Enterprise API. Good fallback provider for North American and UK trade listings.',
    estimatedCostPerCallUSD: 0.004,
  },
  {
    id: 'src_osm_overpass',
    sourceName: 'OpenStreetMap Overpass API',
    sourceType: 'SEARCH_MAPS',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://wiki.openstreetmap.org/wiki/Overpass_API',
    authenticationType: 'PUBLIC_NO_AUTH',
    rateLimitPerMinute: 60,
    termsUrl: 'https://www.openstreetmap.org/copyright',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['name', 'phone', 'website', 'addr:street', 'addr:city', 'addr:postcode', 'craft', 'shop'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Open Data Commons Open Database License (ODbL). Zero-cost open geographical query engine.',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_uk_companies_house',
    sourceName: 'UK Companies House Official API',
    sourceType: 'GOVERNMENT_REGISTRY',
    country: 'GBR',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://developer.company-information.service.gov.uk/',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 600,
    termsUrl: 'https://developer.company-information.service.gov.uk/terms-and-conditions',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['company_name', 'company_number', 'registered_office_address', 'sic_codes', 'company_status', 'date_of_creation'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Official UK Government Registry. Perfect for official UK legal entity verification and SIC code classification (43220 for Plumbing/HVAC, 43210 for Electrical).',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_canada_corporate',
    sourceName: 'Canada Corporations & Provincial Registry',
    sourceType: 'GOVERNMENT_REGISTRY',
    country: 'CAN',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://ised-isde.canada.ca/app/scr/cc/CorporationsSearch/api-info.html',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 120,
    termsUrl: 'https://www.ic.gc.ca/eic/site/icgc.nsf/eng/h_07033.html',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['corporate_name', 'corporation_number', 'registered_office_address', 'status'],
    leadCaptureSupported: false,
    businessDiscoverySupported: true,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Official Canadian federal and provincial corporate registry for verification.',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_inbound_missed_calls',
    sourceName: 'RevenueRecover Inbound Phone & Missed Call Webhook',
    sourceType: 'MISSED_CALL',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'PEST_CONTROL', 'CLEANING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://revenuerecover-ai.vercel.app/api/webhooks/missed-call',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 1000,
    termsUrl: 'https://revenuerecover-ai.vercel.app/security',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['caller_phone', 'contractor_phone', 'call_duration', 'call_timestamp', 'call_status', 'caller_city', 'caller_state'],
    leadCaptureSupported: true,
    businessDiscoverySupported: false,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Direct customer-initiated communication. Fully compliant for automated instantaneous 45-second conversational response.',
    estimatedCostPerCallUSD: 0.0075,
  },
  {
    id: 'src_inbound_web_forms',
    sourceName: 'RevenueRecover Web Form & Widget Ingestor',
    sourceType: 'INBOUND_FORM',
    country: 'GLOBAL',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING', 'SOLAR', 'PEST_CONTROL', 'CLEANING'],
    officialApiAvailable: true,
    apiDocumentationUrl: 'https://revenuerecover-ai.vercel.app/api/leads',
    authenticationType: 'API_KEY',
    rateLimitPerMinute: 1000,
    termsUrl: 'https://revenuerecover-ai.vercel.app/security',
    robotsPolicy: 'ALLOWED',
    dataFieldsAvailable: ['customer_name', 'customer_phone', 'customer_email', 'service_requested', 'postal_code', 'urgency', 'notes'],
    leadCaptureSupported: true,
    businessDiscoverySupported: false,
    integrationStatus: 'CONNECTED',
    enabled: true,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'First-party inbound lead submission with explicit opt-in checkbox.',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_angi_lead_hub',
    sourceName: 'Angi / HomeAdvisor Trade Network',
    sourceType: 'SERVICE_MARKETPLACE',
    country: 'USA',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING'],
    officialApiAvailable: false,
    apiDocumentationUrl: undefined,
    authenticationType: 'PARTNER_ONLY',
    rateLimitPerMinute: 0,
    termsUrl: 'https://www.angi.com/terms.htm',
    robotsPolicy: 'RESTRICTED',
    dataFieldsAvailable: ['business_name', 'rating', 'verified_status'],
    leadCaptureSupported: false,
    businessDiscoverySupported: false,
    integrationStatus: 'NOT_SUPPORTED',
    enabled: false,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Closed ecosystem without public developer API. Marked as PARTNER_ONLY. Direct scraping strictly prohibited.',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_thumbtack_pro',
    sourceName: 'Thumbtack Pro Directory',
    sourceType: 'SERVICE_MARKETPLACE',
    country: 'USA',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'CLEANING'],
    officialApiAvailable: false,
    apiDocumentationUrl: undefined,
    authenticationType: 'PARTNER_ONLY',
    rateLimitPerMinute: 0,
    termsUrl: 'https://www.thumbtack.com/terms/',
    robotsPolicy: 'RESTRICTED',
    dataFieldsAvailable: [],
    leadCaptureSupported: false,
    businessDiscoverySupported: false,
    integrationStatus: 'NOT_SUPPORTED',
    enabled: false,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'Proprietary marketplace. No public API. Requires direct commercial partnership agreement.',
    estimatedCostPerCallUSD: 0.0,
  },
  {
    id: 'src_checkatrade_uk',
    sourceName: 'Checkatrade UK Directory',
    sourceType: 'LOCAL_DIRECTORY',
    country: 'GBR',
    category: ['HVAC', 'PLUMBING', 'ELECTRICAL', 'ROOFING'],
    officialApiAvailable: false,
    apiDocumentationUrl: undefined,
    authenticationType: 'PARTNER_ONLY',
    rateLimitPerMinute: 0,
    termsUrl: 'https://www.checkatrade.com/terms-and-conditions',
    robotsPolicy: 'RESTRICTED',
    dataFieldsAvailable: [],
    leadCaptureSupported: false,
    businessDiscoverySupported: false,
    integrationStatus: 'NOT_SUPPORTED',
    enabled: false,
    lastChecked: new Date().toISOString(),
    complianceNotes: 'No open developer API. Marked as PARTNER_ONLY / NOT_SUPPORTED.',
    estimatedCostPerCallUSD: 0.0,
  },
];

export function getSourceRegistry(): SourceRegistryEntry[] {
  return GLOBAL_SOURCE_REGISTRY;
}

export function getSourceById(id: string): SourceRegistryEntry | undefined {
  return GLOBAL_SOURCE_REGISTRY.find((s) => s.id === id);
}

export function getActiveDiscoverySources(country?: string): SourceRegistryEntry[] {
  return GLOBAL_SOURCE_REGISTRY.filter(
    (s) =>
      s.enabled &&
      s.businessDiscoverySupported &&
      s.integrationStatus === 'CONNECTED' &&
      (country ? s.country === 'GLOBAL' || s.country === country : true)
  );
}
