import {
  Opportunity,
  Customer,
  Conversation,
  Campaign,
  Integration,
  BusinessRules,
  ProspectLead,
  GrowthMetrics,
  Organization,
  Referral,
} from './types';

export const demoOrganization: Organization = {
  id: 'org_summit_hvac',
  name: 'Summit HVAC & Plumbing',
  industry: 'HVAC & Plumbing Services',
  owner_email: 'dave@summithvacpros.com',
  plan: 'growth',
  plan_status: 'active',
  monthly_recovered: 8420,
  lifetime_recovered: 46850,
  created_at: '2026-01-15T08:00:00.000Z',
};

export const demoBusinessRules: BusinessRules = {
  business_hours: {
    start: '08:00',
    end: '18:00',
    timezone: 'America/Chicago',
    work_days: [1, 2, 3, 4, 5, 6],
  },
  quiet_hours: {
    start: '21:00',
    end: '08:00',
  },
  autopilot_mode: 'supervised',
  max_followups: 4,
  followup_interval_days: 2,
  allowed_channels: ['sms', 'email'],
  daily_message_limit: 3,
  monthly_message_limit: 1500,
  kill_switch_active: false,
  discount_rules: {
    max_discount_pct: 10,
    auto_offer_enabled: false,
  },
  escalation_rules: {
    auto_escalate_angry: true,
    auto_escalate_high_ticket: 2500,
  },
};

export const demoGrowthMetrics: GrowthMetrics = {
  visitors: 12480,
  scans: 1842,
  leads: 842,
  qualified_leads: 216,
  demos: 84,
  trials: 57,
  paid_customers: 23,
  mrr: 4827,
  cac: 142,
  ltv: 3200,
  churn_rate: 1.8,
  ai_generated_leads: 610,
  ai_qualified_leads: 183,
  ai_assisted_sales: 19,
  ai_compute_cost: 41.65,
};

export const demoOpportunities: Opportunity[] = [
  {
    id: 'opp_001',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_101',
    customer_name: 'Marcus Sterling',
    customer_phone: '(214) 555-0142',
    customer_email: 'm.sterling@sterlingholdings.com',
    type: 'abandoned_quote',
    estimated_value: 4850,
    confidence_score: 88,
    urgency: 'high',
    recovery_score: 92,
    score_reasons: [
      'High-ticket dual-zone heat pump replacement estimate ($4,850)',
      'Quote delivered 3 days ago with no customer response',
      'Historical customer response window is 48-72 hours',
    ],
    recommended_action: 'Send friendly SMS checking if they need financing options or scheduling review',
    recommended_channel: 'sms',
    status: 'awaiting_approval',
    source: 'ServiceTitan Sync',
    created_at: '2026-08-23T14:30:00Z',
    updated_at: '2026-08-26T08:15:00Z',
  },
  {
    id: 'opp_002',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_102',
    customer_name: 'Elena Rostova',
    customer_phone: '(214) 555-0189',
    customer_email: 'elena.r@dallasrealestate.net',
    type: 'missed_call',
    estimated_value: 1250,
    confidence_score: 94,
    urgency: 'critical',
    recovery_score: 96,
    score_reasons: [
      'Inbound emergency call after 6:00 PM went to voicemail',
      'Caller stayed on line 42 seconds — high intent',
      'Contractor competitors in Dallas have avg 18-minute callback window',
    ],
    recommended_action: 'Instant AI Text-back: "Hi Elena, sorry we missed your call! Can we help with AC emergency dispatch?"',
    recommended_channel: 'sms',
    status: 'detected',
    source: 'Missed Call Webhook',
    created_at: '2026-08-26T09:12:00Z',
    updated_at: '2026-08-26T09:12:00Z',
  },
  {
    id: 'opp_003',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_103',
    customer_name: 'Apex Commercial Plaza',
    customer_phone: '(972) 555-0321',
    customer_email: 'facilities@apexcommercialplaza.com',
    type: 'overdue_invoice',
    estimated_value: 3400,
    confidence_score: 85,
    urgency: 'medium',
    recovery_score: 82,
    score_reasons: [
      'Invoice #4092 is 18 days past due for commercial chiller maintenance',
      'Long-term client with 4 years on file, never defaulted',
      'Accounting email bounce detected on primary contact',
    ],
    recommended_action: 'Send automated invoice statement with 1-click Stripe payment link to facilities director',
    recommended_channel: 'email',
    status: 'contacted',
    source: 'QuickBooks Sync',
    created_at: '2026-08-10T11:00:00Z',
    updated_at: '2026-08-24T16:00:00Z',
    last_message_sent: '2026-08-24T16:00:00Z',
  },
  {
    id: 'opp_004',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_104',
    customer_name: 'David & Sarah Chen',
    customer_phone: '(469) 555-0784',
    customer_email: 'chen.family.dallas@gmail.com',
    type: 'dormant_customer',
    estimated_value: 890,
    confidence_score: 76,
    urgency: 'low',
    recovery_score: 78,
    score_reasons: [
      'Last seasonal AC tune-up completed 11 months ago',
      'Carrier warranty requires annual documented maintenance check',
      'High propensity for pre-winter furnace inspection add-on',
    ],
    recommended_action: 'Send seasonal VIP loyalty tune-up reactivation offer ($49 filter credit included)',
    recommended_channel: 'sms',
    status: 'detected',
    source: 'CRM Inactive Sweep',
    created_at: '2026-08-20T08:00:00Z',
    updated_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'opp_005',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_105',
    customer_name: 'Robert Thorne',
    customer_phone: '(214) 555-0955',
    customer_email: 'rthorne@thornegroup.org',
    type: 'failed_payment',
    estimated_value: 1650,
    confidence_score: 91,
    urgency: 'high',
    recovery_score: 89,
    score_reasons: [
      'Recurring quarterly maintenance agreement payment failed (expired credit card)',
      'Account active for 22 months',
    ],
    recommended_action: 'Send secure card update link with instant retry',
    recommended_channel: 'email',
    status: 'recovered',
    source: 'Stripe Webhook',
    created_at: '2026-08-14T09:00:00Z',
    updated_at: '2026-08-16T11:20:00Z',
    recovered_amount: 1650,
    recovered_at: '2026-08-16T11:20:00Z',
  },
  {
    id: 'opp_006',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_106',
    customer_name: 'Samantha Wright',
    customer_phone: '(972) 555-0418',
    customer_email: 'swright77@yahoo.com',
    type: 'cancelled_appointment',
    estimated_value: 750,
    confidence_score: 82,
    urgency: 'medium',
    recovery_score: 84,
    score_reasons: [
      'Cancelled water heater flush appointment due to work travel conflict',
      'Expressed desire to reschedule for next week',
    ],
    recommended_action: 'Send personalized calendar rebooking link with morning slots',
    recommended_channel: 'sms',
    status: 'recovered',
    source: 'Google Calendar Sync',
    created_at: '2026-08-18T10:00:00Z',
    updated_at: '2026-08-20T14:30:00Z',
    recovered_amount: 750,
    recovered_at: '2026-08-20T14:30:00Z',
  },
  {
    id: 'opp_007',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_107',
    customer_name: 'Oakridge Business Park',
    customer_phone: '(214) 555-0812',
    customer_email: 'manager@oakridgepark.com',
    type: 'abandoned_quote',
    estimated_value: 6020,
    confidence_score: 90,
    urgency: 'high',
    recovery_score: 91,
    score_reasons: [
      'Commercial duct replacement estimate ($6,020) viewed 4 times by board members',
      'No decision logged after 6 days',
    ],
    recommended_action: 'Send follow-up addressing rebate & tax credit incentives available this month',
    recommended_channel: 'email',
    status: 'recovered',
    source: 'ServiceTitan Sync',
    created_at: '2026-08-05T09:00:00Z',
    updated_at: '2026-08-12T15:00:00Z',
    recovered_amount: 6020,
    recovered_at: '2026-08-12T15:00:00Z',
  },
];

export const demoCustomers: Customer[] = [
  {
    id: 'cust_101',
    organization_id: 'org_summit_hvac',
    name: 'Marcus Sterling',
    email: 'm.sterling@sterlingholdings.com',
    phone: '(214) 555-0142',
    address: '4420 Preston Rd, Highland Park, TX 75205',
    lifetime_value: 14200,
    total_purchases: 5,
    last_purchase_date: '2025-11-10T10:00:00Z',
    last_contact_date: '2026-08-23T14:30:00Z',
    status: 'at_risk',
    tags: ['VIP Residential', 'High-Ticket', 'Heat Pump'],
    open_opportunities_count: 1,
    ai_summary: 'Premium residential client with dual 4-ton systems. Frequently accepts quotes when financing or seasonal scheduling incentives are presented.',
    next_recommended_action: 'Send Heat Pump Quote Follow-Up with financing terms.',
  },
  {
    id: 'cust_102',
    organization_id: 'org_summit_hvac',
    name: 'Elena Rostova',
    email: 'elena.r@dallasrealestate.net',
    phone: '(214) 555-0189',
    address: '1820 McKinney Ave #1400, Dallas, TX 75201',
    lifetime_value: 3100,
    total_purchases: 2,
    last_purchase_date: '2025-06-18T14:00:00Z',
    last_contact_date: '2026-08-26T09:12:00Z',
    status: 'active',
    tags: ['Property Manager', 'Emergency Inbound'],
    open_opportunities_count: 1,
    ai_summary: 'Manages 12 luxury residential rentals. Requires fast dispatch response time.',
    next_recommended_action: 'Dispatch technician or send instant text booking confirmation.',
  },
  {
    id: 'cust_103',
    organization_id: 'org_summit_hvac',
    name: 'Apex Commercial Plaza',
    email: 'facilities@apexcommercialplaza.com',
    phone: '(972) 555-0321',
    address: '7800 LBJ Freeway, Dallas, TX 75240',
    lifetime_value: 28900,
    total_purchases: 14,
    last_purchase_date: '2026-07-28T09:00:00Z',
    last_contact_date: '2026-08-24T16:00:00Z',
    status: 'active',
    tags: ['Commercial', 'Quarterly Maintenance', 'Net-30'],
    open_opportunities_count: 1,
    ai_summary: 'High-value commercial property. Reliable payer but corporate billing portal often requires automated statement reminders.',
    next_recommended_action: 'Resend payment link with detailed itemized PO receipt.',
  },
  {
    id: 'cust_104',
    organization_id: 'org_summit_hvac',
    name: 'David & Sarah Chen',
    email: 'chen.family.dallas@gmail.com',
    phone: '(469) 555-0784',
    address: '3104 Willowbrook Ln, Plano, TX 75093',
    lifetime_value: 4600,
    total_purchases: 3,
    last_purchase_date: '2025-09-14T11:00:00Z',
    last_contact_date: '2026-08-20T08:00:00Z',
    status: 'dormant',
    tags: ['Residential', 'Annual Maintenance Agreement'],
    open_opportunities_count: 1,
    ai_summary: 'Loyal customer for 3 years. Due for 12-month AC and furnace tune-up.',
    next_recommended_action: 'Send seasonal tune-up reactivation reminder.',
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'conv_001',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_101',
    customer_name: 'Marcus Sterling',
    customer_phone: '(214) 555-0142',
    customer_email: 'm.sterling@sterlingholdings.com',
    channel: 'sms',
    status: 'needs_reply',
    ai_classification: 'pricing_question',
    ai_suggested_reply: 'Hi Marcus! Yes, we offer 0% APR financing for 18 months on the Carrier Infinity system. Would you like me to email you the quick 60-second approval link?',
    ai_confidence: 94,
    updated_at: '2026-08-26T09:40:00Z',
    messages: [
      {
        id: 'msg_1',
        sender: 'ai_agent',
        text: 'Hi Marcus, Dave from Summit HVAC here following up on your heat pump estimate from Tuesday. We have an installation crew available in Highland Park this Friday—did you have any questions on the equipment specs?',
        timestamp: '2026-08-26T08:30:00Z',
        channel: 'sms',
        status: 'delivered',
      },
      {
        id: 'msg_2',
        sender: 'customer',
        text: 'Hey Dave, I saw the quote. Do you guys have any financing options or 0% interest terms available right now?',
        timestamp: '2026-08-26T09:38:00Z',
        channel: 'sms',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'conv_002',
    organization_id: 'org_summit_hvac',
    customer_id: 'cust_102',
    customer_name: 'Elena Rostova',
    customer_phone: '(214) 555-0189',
    customer_email: 'elena.r@dallasrealestate.net',
    channel: 'sms',
    status: 'ai_handling',
    ai_classification: 'ready_to_book',
    ai_suggested_reply: 'Got it! Our tech Leo is on call in Uptown and can be at your McKinney Ave property between 11:30 AM and 1:00 PM today. Does that work for you?',
    ai_confidence: 97,
    updated_at: '2026-08-26T09:20:00Z',
    messages: [
      {
        id: 'msg_3',
        sender: 'ai_agent',
        text: 'Hi Elena! We saw your missed call to Summit HVAC dispatch. Are you experiencing an AC or plumbing issue at one of your properties?',
        timestamp: '2026-08-26T09:13:00Z',
        channel: 'sms',
        status: 'delivered',
      },
      {
        id: 'msg_4',
        sender: 'customer',
        text: 'Yes! AC stopped blowing cold in unit 4B. Need someone out today if possible.',
        timestamp: '2026-08-26T09:18:00Z',
        channel: 'sms',
        status: 'delivered',
      },
    ],
  },
];

export const demoCampaigns: Campaign[] = [
  {
    id: 'camp_001',
    organization_id: 'org_summit_hvac',
    name: 'High-Ticket Quote Recovery Sequence',
    type: 'quote_recovery',
    status: 'active',
    steps: [
      { id: 's1', delay_days: 2, channel: 'sms', template: 'Hi {{name}}, following up on your {{service}} quote. Did you have any questions on the installation timeline?' },
      { id: 's2', delay_days: 4, channel: 'email', template: 'Subject: Options for your {{service}} project at {{address}}\n\nHi {{name}},\nWe wanted to share financing options and rebate details...' },
      { id: 's3', delay_days: 8, channel: 'sms', template: 'Hi {{name}}, our seasonal quote lock expires this Friday. Let us know if you would like to hold your slot!' },
    ],
    stats: {
      sent: 84,
      opened: 76,
      replied: 38,
      recovered_count: 14,
      recovered_revenue: 38400,
    },
  },
  {
    id: 'camp_002',
    organization_id: 'org_summit_hvac',
    name: 'Missed Call Instant Text-Back',
    type: 'lead_recovery',
    status: 'active',
    steps: [
      { id: 's4', delay_days: 0, channel: 'sms', template: 'Hi! Sorry we missed your call at Summit HVAC. How can our dispatch team help you today?' },
    ],
    stats: {
      sent: 142,
      opened: 139,
      replied: 91,
      recovered_count: 32,
      recovered_revenue: 29800,
    },
  },
  {
    id: 'camp_003',
    organization_id: 'org_summit_hvac',
    name: 'Dormant Seasonal Customer Reactivation',
    type: 'customer_reactivation',
    status: 'active',
    steps: [
      { id: 's5', delay_days: 0, channel: 'sms', template: 'Hi {{name}}, it has been 10 months since your last HVAC service. Schedule your VIP tune-up this week and get a free filter replacement!' },
      { id: 's6', delay_days: 5, channel: 'email', template: 'Subject: Your HVAC Warranty Maintenance Due\n\nProtect your system efficiency before the Texas heat...' },
    ],
    stats: {
      sent: 210,
      opened: 165,
      replied: 52,
      recovered_count: 22,
      recovered_revenue: 16200,
    },
  },
];

export const demoIntegrations: Integration[] = [
  {
    id: 'int_001',
    organization_id: 'org_summit_hvac',
    provider: 'servicetitan',
    name: 'ServiceTitan',
    category: 'CRM',
    status: 'connected',
    mode: 'demo',
    last_sync_at: '2026-08-26T10:00:00Z',
    sync_count: 580,
  },
  {
    id: 'int_002',
    organization_id: 'org_summit_hvac',
    provider: 'stripe',
    name: 'Stripe Payments',
    category: 'Payments',
    status: 'connected',
    mode: 'demo',
    last_sync_at: '2026-08-26T09:45:00Z',
    sync_count: 142,
  },
  {
    id: 'int_003',
    organization_id: 'org_summit_hvac',
    provider: 'twilio',
    name: 'Twilio SMS Gateway',
    category: 'Communication',
    status: 'connected',
    mode: 'demo',
    last_sync_at: '2026-08-26T10:15:00Z',
    sync_count: 890,
  },
  {
    id: 'int_004',
    organization_id: 'org_summit_hvac',
    provider: 'google_calendar',
    name: 'Google Calendar Dispatch',
    category: 'Calendar',
    status: 'connected',
    mode: 'demo',
    last_sync_at: '2026-08-26T10:10:00Z',
    sync_count: 45,
  },
  {
    id: 'int_005',
    organization_id: 'org_summit_hvac',
    provider: 'quickbooks',
    name: 'QuickBooks Online',
    category: 'Accounting',
    status: 'connected',
    mode: 'demo',
    last_sync_at: '2026-08-26T08:00:00Z',
    sync_count: 320,
  },
  {
    id: 'int_006',
    organization_id: 'org_summit_hvac',
    provider: 'housecall_pro',
    name: 'Housecall Pro',
    category: 'CRM',
    status: 'disconnected',
    mode: 'mock',
  },
];

export const demoProspectLeads: ProspectLead[] = [
  {
    id: 'pros_001',
    business_name: 'Lone Star Climate Pros',
    website: 'https://lonestarclimatepros.example.com',
    industry: 'HVAC & AC Repair',
    city: 'Fort Worth',
    state: 'Texas',
    business_size: '12-25 technicians',
    public_email: 'info@lonestarclimatepros.example.com',
    public_phone: '(817) 555-0199',
    source: 'public_directory',
    lead_score: 94,
    tier: 'hot',
    estimated_leakage: 24800,
    confidence: 89,
    stage: 'qualified',
    research_dossier: {
      signals: [
        'Online quote request form detected on homepage',
        'No immediate 2-minute SMS confirmation triggered',
        'Avg 4.8 star Google rating with 180+ reviews',
        'Offers high-ticket system replacements ($6,000+)',
      ],
      missed_call_risk: 'High — peak afternoon call volume exceeds dispatch capacity',
      quote_workflow: 'Sends email PDF estimates without automated multi-day SMS re-engagement',
      online_booking_present: true,
      recommended_pitch: 'Recover missed HVAC leads and abandoned replacement quotes automatically in Fort Worth.',
    },
    personalized_outreach: {
      subject: 'Quick idea for Lone Star Climate Pros',
      email_body: 'Hi team,\n\nI noticed Lone Star Climate Pros offers online service requests in Fort Worth. We built RevenueRecover AI to help Texas HVAC businesses recover missed calls, abandoned estimates, and dormant customers automatically.\n\nFor contractors with high-value jobs, recovering even 2-3 extra installs per month adds $15,000+ to your bottom line.\n\nYou can see an estimated revenue scan here.',
      sms_body: 'Hi! Loved Lone Star Climate Pros reviews in Fort Worth. We built an AI tool that recovers missed HVAC calls & abandoned estimates automatically. Would love to send a 60-second revenue leak report if interested?',
    },
    next_action: 'Send personalized email outreach campaign #1',
    opt_out: false,
    created_at: '2026-08-24T10:00:00Z',
  },
  {
    id: 'pros_002',
    business_name: 'Alamo City Plumbing & Rooter',
    website: 'https://alamoplumbingpros.example.com',
    industry: 'Plumbing',
    city: 'San Antonio',
    state: 'Texas',
    business_size: '8-15 trucks',
    public_email: 'service@alamoplumbingpros.example.com',
    public_phone: '(210) 555-0872',
    source: 'public_directory',
    lead_score: 89,
    tier: 'hot',
    estimated_leakage: 18500,
    confidence: 84,
    stage: 'contacted',
    research_dossier: {
      signals: [
        'Specializes in emergency slab leak & water heater replacements ($2,200 avg)',
        'Phone dispatch voicemail during weekend emergency hours',
        '92 Google reviews',
      ],
      missed_call_risk: 'Critical after 5 PM and weekends',
      quote_workflow: 'Manual technician phone follow-ups with low callback rate',
      online_booking_present: false,
      recommended_pitch: 'Capture every 24/7 plumbing emergency lead before they call competitors.',
    },
    personalized_outreach: {
      subject: 'After-hours plumbing lead capture for Alamo City Plumbing',
      email_body: 'Hi folks,\n\nSan Antonio homeowners facing water heater leaks call the first plumber who replies. RevenueRecover AI texts back missed calls within 45 seconds and books the appointment on your calendar automatically.\n\nHappy to share a quick interactive demo if helpful.',
      sms_body: 'Hi Alamo Plumbing! We help San Antonio plumbing pros recover missed after-hours calls instantly via AI text-back. Want to check your free recovery estimate?',
    },
    last_contacted_at: '2026-08-25T14:00:00Z',
    next_action: 'Follow-up Day 2 value reminder',
    opt_out: false,
    created_at: '2026-08-23T11:30:00Z',
  },
  {
    id: 'pros_003',
    business_name: 'Sunbelt Premier Roofing',
    website: 'https://sunbeltroofing.example.com',
    industry: 'Roofing & Solar',
    city: 'Phoenix',
    state: 'Arizona',
    business_size: '20+ crew',
    public_email: 'estimates@sunbeltroofing.example.com',
    public_phone: '(602) 555-0433',
    source: 'verified_api',
    lead_score: 92,
    tier: 'hot',
    estimated_leakage: 36000,
    confidence: 91,
    stage: 'demo',
    research_dossier: {
      signals: [
        'Storm damage insurance estimates avg $12,500/job',
        'Homeowner decision cycles take 14-30 days',
        'Lacks automated multi-week insurance claim nurturing sequence',
      ],
      missed_call_risk: 'Moderate',
      quote_workflow: 'Paper/Email quote delivery with steep 45% drop-off',
      online_booking_present: true,
      recommended_pitch: 'Automate 30-day insurance claim follow-up and recover $36K/mo in roofing bids.',
    },
    next_action: 'Run interactive demo simulation with Phoenix roofing metrics',
    opt_out: false,
    created_at: '2026-08-22T09:00:00Z',
  },
  {
    id: 'pros_004',
    business_name: 'Metro Electric & Smart Home',
    website: 'https://metroelectricpros.example.com',
    industry: 'Electrical',
    city: 'Austin',
    state: 'Texas',
    business_size: '5-10 technicians',
    public_email: 'contact@metroelectricpros.example.com',
    public_phone: '(512) 555-0911',
    source: 'public_directory',
    lead_score: 78,
    tier: 'warm',
    estimated_leakage: 12400,
    confidence: 80,
    stage: 'new_lead',
    research_dossier: {
      signals: [
        'EV charger installations and panel upgrades ($2,500 - $5,000)',
        'Quote turnaround is fast but follow-up is manual',
      ],
      missed_call_risk: 'Medium',
      quote_workflow: 'Quickbooks estimates sent without automated reminders',
      online_booking_present: false,
      recommended_pitch: 'Turn panel upgrade and EV charger inquiries into scheduled installs.',
    },
    next_action: 'Run AI Prospect Research & scoring',
    opt_out: false,
    created_at: '2026-08-25T16:00:00Z',
  },
];

export const demoReferrals: Referral[] = [
  {
    id: 'ref_001',
    referrer_org_id: 'org_summit_hvac',
    referrer_name: 'Dave Miller (Summit HVAC)',
    referral_code: 'SUMMIT-1FREE',
    referred_business: 'Lone Star Climate Pros',
    referred_email: 'mike@lonestarclimatepros.example.com',
    status: 'active_customer',
    reward: '1 Month Free Growth Plan ($149 credit applied)',
    created_at: '2026-08-10T12:00:00Z',
  },
  {
    id: 'ref_002',
    referrer_org_id: 'org_summit_hvac',
    referrer_name: 'Dave Miller (Summit HVAC)',
    referral_code: 'SUMMIT-1FREE',
    referred_business: 'Precision Mechanical Dallas',
    referred_email: 'service@precisiondallas.example.com',
    status: 'invited',
    reward: 'Pending Activation ($149 credit on signup)',
    created_at: '2026-08-22T14:30:00Z',
  },
];
